rails-app/config/routes.rb
Rails.application.routes.draw do
  resources :bagged_summits
  resources :routes
  devise_for :users
  resources :hikes
  root 'home#index'
  get 'home/index', to: "home#index"
  # get 'summits', to: "summits#index"
  resources :summits
end

rails-app/app/models/bagged_summit.rb
class BaggedSummit < ApplicationRecord
  belongs_to :summit
  belongs_to :user
end

rails-app/app/controllers/bagged_summits_controller.rb
class BaggedSummitsController < ApplicationController
  before_action :set_bagged_summit, only: %i[ show edit update destroy ]

  before_action :authenticate_user!

  # GET /bagged_summits or /bagged_summits.json
  def index
    @bagged_summits = BaggedSummit.all
  end

  # GET /bagged_summits/1 or /bagged_summits/1.json
  def show
  end

  # GET /bagged_summits/new
  def new
    @bagged_summit = BaggedSummit.new
  end

  # GET /bagged_summits/1/edit
  def edit
  end

  # POST /bagged_summits or /bagged_summits.json
  def create
    @bagged_summit = BaggedSummit.new(bagged_summit_params)
    print @bagged_summit
    print '<<<<<><>>>>>>'
    @bagged_summit.user_id = current_user.id
    print @bagged_summit

    respond_to do |format|
      if @bagged_summit.save
        format.html { redirect_to @bagged_summit, notice: "Bagged summit was successfully created." }
        format.json { render :show, status: :created, location: @bagged_summit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bagged_summit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bagged_summits/1 or /bagged_summits/1.json
  def update
    respond_to do |format|
      if @bagged_summit.update(bagged_summit_params)
        format.html { redirect_to @bagged_summit, notice: "Bagged summit was successfully updated." }
        format.json { render :show, status: :ok, location: @bagged_summit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bagged_summit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bagged_summits/1 or /bagged_summits/1.json
  def destroy
    @bagged_summit.destroy
    respond_to do |format|
      format.html { redirect_to bagged_summits_url, notice: "Bagged summit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bagged_summit
      @bagged_summit = BaggedSummit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bagged_summit_params
      params.require(:bagged_summit).permit(:datetime, :summit_id, :user_id)
    end
end

rails-app/app/helpers/bagged_summits_helper.rb
module BaggedSummitsHelper
end

rails-app/app/views/bagged_summits/_form.html.erb
<%= form_with(model: bagged_summit) do |form| %>
  <% if bagged_summit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bagged_summit.errors.count, "error") %> prohibited this bagged_summit from being saved:</h2>

      <ul>
        <% bagged_summit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :datetime, 'When did you bag this summit?' %>
    <%= form.date_select :datetime %>
  </div>

  <div class="field">
    <%= form.label :summit_id, 'Summit ID' %>
    <%= form.text_field :summit_id %>
    <script>
    (() => {
      let urlSearchParams = new URLSearchParams(window.location.search);
      let params = Object.fromEntries(urlSearchParams.entries());
      if (!params.summit_id) {
        //TODO: display searchable list of summits
        alert('Sorry, there should be a ?summit_ID= in the url but the code isn\'t picking it up. It\'s on the TODO list to add a searchable list of summits but for now you\'ll just have to forgive me I\'m afraid.')
      } else {
        //set form field to summit id
        //#bagged_summit_summit_id
        document.getElementById('bagged_summit_summit_id').value = params.summit_id;
      }
    })()
    </script>
  </div>

  <div class="field">
    user ID - set server side in the controller for currently logged in user.
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit 'Bag it' %>
  </div>
<% end %>

rails-app/app/views/bagged_summits/edit.html.erb
<h1>Editing Bagged Summit</h1>

<%= render 'form', bagged_summit: @bagged_summit %>

<%= link_to 'Show', @bagged_summit %> |
<%= link_to 'Back', bagged_summits_path %>

rails-app/app/views/bagged_summits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bagged Summits</h1>

<table>
  <thead>
    <tr>
      <th>Datetime</th>
      <th>Summit</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bagged_summits.each do |bagged_summit| %>
      <tr>
        <td><%= bagged_summit.datetime %></td>
        <td><%= bagged_summit.summit_id %></td>
        <td><%= bagged_summit.user_id %></td>
        <td><%= link_to 'Show', bagged_summit %></td>
        <td><%= link_to 'Edit', edit_bagged_summit_path(bagged_summit) %></td>
        <td><%= link_to 'Destroy', bagged_summit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Bagged Summit', new_bagged_summit_path %>

rails-app/app/views/bagged_summits/new.html.erb
<h1>New Bagged Summit</h1>

<%= render 'form', bagged_summit: @bagged_summit %>

<%= link_to 'Back', bagged_summits_path %>

rails-app/app/views/bagged_summits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Datetime:</strong>
  <%= @bagged_summit.datetime %>
</p>

<p>
  <strong>Summit:</strong>
  <%= @bagged_summit.summit_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @bagged_summit.user_id %>
</p>

<%= link_to 'Edit', edit_bagged_summit_path(@bagged_summit) %> |
<%= link_to 'Back', bagged_summits_path %>