rails-app/config/routes.rb
Rails.application.routes.draw do
  resources :bagged_summits
  resources :routes
  devise_for :users
  resources :hikes
  root 'home#index'
  get 'home/index', to: "home#index"
  # get 'summits', to: "summits#index"
  resources :summits
end

rails-app/app/models/hike.rb
class Hike < ApplicationRecord
  has_many :users, through: :hikes_user
  has_many :summits, through: :hikes_summit
  belongs_to :route
end

rails-app/app/controllers/hikes_controller.rb
class HikesController < ApplicationController
  before_action :set_hike, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :is_participant, only: [:show, :edit, :update, :destroy]

  # GET /hikes or /hikes.json
  def index
    # TODO: only show hikes by the current_user
    # @hikes = Hike.find_by
  end

  # GET /hikes/1 or /hikes/1.json
  def show
  end

  # GET /hikes/new
  def new
    @hike = Hike.new
  end

  # GET /hikes/1/edit
  def edit
  end

  # POST /hikes or /hikes.json
  def create
    @hike = Hike.new(hike_params)

    # TODO: add current_user as hike author / user / relation / association

    respond_to do |format|
      if @hike.save
        format.html { redirect_to @hike, notice: "Hike was successfully created." }
        format.json { render :show, status: :created, location: @hike }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hikes/1 or /hikes/1.json
  def update

    # TODO: user can only remove themselves from association, not others

    respond_to do |format|
      if @hike.update(hike_params)
        format.html { redirect_to @hike, notice: "Hike was successfully updated." }
        format.json { render :show, status: :ok, location: @hike }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hikes/1 or /hikes/1.json
  def destroy

    # TODO: user can only destroy a hike if there are no other users associated with it.

    @hike.destroy
    respond_to do |format|
      format.html { redirect_to hikes_url, notice: "Hike was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # TODO: action to check if the user makeing a request is one of the Hike participants (relationship / association)
  # def is_participant 
  #   @participant = 
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hike
      @hike = Hike.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hike_params
      params.require(:hike).permit(:date, :description, :title)
    end
end

rails-app/app/helpers/hikes_helper.rb
module HikesHelper
end

rails-app/app/views/hikes/_form.html.erb
<%= form_with(model: hike) do |form| %>
  <% if hike.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hike.errors.count, "error") %> prohibited this hike from being saved:</h2>

      <ul>
        <% hike.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rails-app/app/views/hikes/edit.html.erb
<h1>Editing Hike</h1>

<%= render 'form', hike: @hike %>

<%= link_to 'Show', @hike %> |
<%= link_to 'Back', hikes_path %>

rails-app/app/views/hikes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hikes</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Description</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hikes.each do |hike| %>
      <tr>
        <td><%= hike.date %></td>
        <td><%= hike.description %></td>
        <td><%= hike.title %></td>
        <td><%= link_to 'Show', hike %></td>
        <td><%= link_to 'Edit', edit_hike_path(hike) %></td>
        <td><%= link_to 'Destroy', hike, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hike', new_hike_path %>

rails-app/app/views/hikes/new.html.erb
<h1>New Hike</h1>

<%= render 'form', hike: @hike %>

<%= link_to 'Back', hikes_path %>

rails-app/app/views/hikes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @hike.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @hike.description %>
</p>

<p>
  <strong>Title:</strong>
  <%= @hike.title %>
</p>

<%= link_to 'Edit', edit_hike_path(@hike) %> |
<%= link_to 'Back', hikes_path %>