rails-app/config/routes.rb
Rails.application.routes.draw do
  resources :bagged_summits
  resources :routes
  devise_for :users
  resources :hikes
  root 'home#index'
  get 'home/index', to: "home#index"
  # get 'summits', to: "summits#index"
  resources :summits
end

rails-app/app/models/route.rb
class Route < ApplicationRecord
  has_many :users, through: :route_user
  has_many :summits, through: :route_summit
  has_many :hikes
end

rails-app/app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /routes or /routes.json
  def index
    @routes = Route.all
  end

  # GET /routes/1 or /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes or /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      if @route.save
        format.html { redirect_to @route, notice: "Route was successfully created." }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1 or /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: "Route was successfully updated." }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1 or /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: "Route was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def route_params
      params.require(:route).permit(:name, :description)
    end
end

rails-app/app/helpers/routes_helper.rb
module RoutesHelper
end

rails-app/app/views/routes/_form.html.erb
<%= form_with(model: route) do |form| %>
  <% if route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
        <% route.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rails-app/app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

rails-app/app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Routes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.name %></td>
        <td><%= route.description %></td>
        <td><%= link_to 'Show', route %></td>
        <td><%= link_to 'Edit', edit_route_path(route) %></td>
        <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Route', new_route_path %>

rails-app/app/views/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Back', routes_path %>

rails-app/app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @route.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @route.description %>
</p>

<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>