rails-app/config/routes.rb
Rails.application.routes.draw do
  resources :bagged_summits
  resources :routes
  devise_for :users
  resources :hikes
  root 'home#index'
  get 'home/index', to: "home#index"
  # get 'summits', to: "summits#index"
  resources :summits
end

rails-app/app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Summits", summits_path, class:"nav-link" %>
          </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Hikes", hikes_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Profile", edit_user_registration_path, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Register", new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log In", new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
    </div>
  </div>
</nav>

rails-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby Mountain</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100;400&display=swap" rel="stylesheet"> 
  </head>

  <body>

    <%= render "layouts/nav" %>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
</html>